name: PayNow
author: PayNow
version: ${version}
api-version: 1.13
main: gg.paynow.paynowbukkit.PayNowBukkit

commands:
  paynow:
    description: PayNow command
    usage: /paynow
    permission: paynow.admin
    aliases: [pn]